//
//  GenerateCodeUseCase.swift
//  Swifont
//
//  Created by JK on 15/1/26.
//

import Foundation

final class GenerateCodeUseCase {
    private let repository: FontRepositoryProtocol

    init(repository: FontRepositoryProtocol) {
        self.repository = repository
    }

    func execute(family: FontFamily) -> GeneratedCode {
        repository.generateCode(for: family)
    }

    func execute(families: [FontFamily]) -> [GeneratedCode] {
        repository.generateCode(for: families)
    }

    func executeCombined(families: [FontFamily]) -> String {
        let codes = repository.generateCode(for: families)
        let header = """
        //
        //  Font+Extensions.swift
        //  Generated by Swifont
        //  \(formattedDate())
        //

        import SwiftUI
        import UIKit

        """

        let body = codes.map(\.code).joined(separator: "\n\n")
        return header + body
    }

    private func formattedDate() -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd HH:mm:ss"
        return formatter.string(from: Date())
    }
}
